apiVersion: v1
kind: ConfigMap
metadata:
  name: pmgen-config
  namespace: telecom-analytics
  labels:
    app.kubernetes.io/name: pmgen
    app.kubernetes.io/component: telemetry-producer
    app.kubernetes.io/part-of: cloud-native-telecom-analytics
data:
  PMGEN_KAFKA_BROKER: redpanda.data-services.svc.cluster.local:9092
  PMGEN_KAFKA_TOPIC: pm.events
  PMGEN_TARGET_URL: http://ingest.telecom-analytics.svc.cluster.local:3000/v1/events
  PMGEN_INTERVAL_SECONDS: "5"
  PMGEN_CELL_COUNT: "50"
  PMGEN_SOURCE: pmgen
  PMGEN_SCHEMA_VERSION: "1"
  PMGEN_SCENARIO: steady
  PMGEN_REQUEST_TIMEOUT_SECONDS: "5"
  PMGEN_PROMETHEUS_PORT: "8000"
