apiVersion: v1
kind: Service
metadata:
  name: pmgen
  namespace: telecom-analytics
  labels:
    app.kubernetes.io/name: pmgen
    app.kubernetes.io/component: telemetry-producer
    app.kubernetes.io/part-of: cloud-native-telecom-analytics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pmgen
  ports:
    - name: http
      port: 8000
      targetPort: http
