apiVersion: 1

datasources:
  - name: Postgres
    uid: grafana-postgresql-datasource
    type: postgres
    access: proxy
    url: postgres.data-services.svc.cluster.local:5432
    user: telecom
    secureJsonData:
      password: telecom
    jsonData:
      database: telecom
      sslmode: disable
      postgresVersion: 1800
      timescaledb: false
    isDefault: true
    editable: false

  - name: Prometheus
    uid: grafana-prometheus-datasource
    type: prometheus
    access: proxy
    url: http://prometheus.monitoring.svc.cluster.local:9090/
    isDefault: false
    editable: false
