apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-credentials
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: visualization
    app.kubernetes.io/part-of: cloud-native-telecom-analytics
type: Opaque
stringData:
  POSTGRES_USER: telecom
  POSTGRES_PASSWORD: telecom
  POSTGRES_DB: telecom
