apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/component: metrics-exporter
    app.kubernetes.io/part-of: cloud-native-telecom-analytics
data:
  DATA_SOURCE_URI: postgres.data-services.svc.cluster.local:5432/telecom?sslmode=disable
  PG_EXPORTER_COLLECTION_TIMEOUT: 10s
