{
 "title": "RAN KPIs",
 "tags": [
  "phase0",
  "telecom"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Call/Session Drop Rate Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  drop_rate_pct_avg AS value\nFROM analytics.v_kpi_utilization_1m\nWHERE $__timeFilter(ts)\nORDER BY ts;\n"
    }
   ]
  },
  {
   "title": "Average UL PRB Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  ul_prb_util_pct_avg AS value\nFROM analytics.v_kpi_utilization_1m\nWHERE $__timeFilter(ts)\nORDER BY ts;"
    }
   ]
  },
  {
   "title": "Average DL PRB Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  dl_prb_util_pct_avg AS value\nFROM analytics.v_kpi_utilization_1m\nWHERE $__timeFilter(ts)\nORDER BY ts;"
    }
   ]
  },
  {
   "title": "Average RRC Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  rrc_conn_avg AS value\nFROM analytics.v_kpi_utilization_1m\nWHERE $__timeFilter(ts)\nORDER BY ts;\n"
    }
   ]
  }
 ]
}