name: analytics

services:

  console:
    image: redpandadata/console:v3.7.0
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: redpanda:9092
    ports:
      - "18080:8080"
    depends_on:
      - redpanda
    networks:
      - analytics-net

volumes:
  redpanda_data: