apiVersion: v1
kind: Secret
metadata:
  name: ingest-db-credentials
  namespace: telecom-analytics
  labels:
    app.kubernetes.io/name: ingest
    app.kubernetes.io/component: event-consumer
    app.kubernetes.io/part-of: cloud-native-telecom-analytics
type: Opaque
stringData:
  PGPASSWORD: telecom
