apiVersion: v1
kind: Service
metadata:
  name: ingest
  namespace: telecom-analytics
  labels:
    app.kubernetes.io/name: ingest
    app.kubernetes.io/component: event-consumer
    app.kubernetes.io/part-of: cloud-native-telecom-analytics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ingest
  ports:
    - name: http
      port: 3000
      targetPort: http
